### ISSUE TITLE
Cocktail Item | fix blink when moving from AR tab back to recipe tab, and tooltip is still in show position

### ISSUE THREAD

**Issue by zoharHenMicrosoft** [zoharhen/Cocktails#43]
@shahafhermann low priority, as the current blink happens only 1 time, and only for a second. am I right?

**Comment by shahafhermann** [comment]
@zoharHenMicrosoft I'm not sure. This is a pretty noticeable UX issue, and it's guaranteed that EVERY user will encounter it at least once.
Also, as far as I know it happens for every transition of the first cocktail (after new installation) and only gets fixed when going back to the scrolling view.
If you have other more pressing things to complete, try pushing everything you've done and I'll take a shot at it.

**Comment by zoharhen** [comment]
@shahafhermann please let me know if you managed to fix it, otherwise, we will switch the tabbed view to activity with floating-action-button. something like that https://images.app.goo.gl/CmFbmzp47u17rEKA6. WDYT?

**Comment by shahafhermann** [comment]
Tooltip now doesn't suppose to show a second time after granting camera access.
The "blink" does happen once after granting access. The reason is that the second tooltip is actually initialized a second time and then immediately dismissed - the dismiss operation is the one giving us trouble, couldn't find why it is initialized a second time in the first place.
You might want to give it another look and understand what makes it show again, switch to the layout you offered (might take some serious work since we really rely on the fragment setup), or just choose to live with this issue.

**Comment by enavhasson** [comment]
The blink appears every time  I switch from the AR tab back to recipe tab (with and without the tooltip).

**Comment by zoharhen** [comment]
won't fix
